### ISSUE TITLE
Feature Request : Add ALIAS support (preview)

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [octodns/octodns-googlecloud#22]
Hi Ross, 

As per [Ref](https://cloud.google.com/dns/docs/records-overview?hl=en) Cloud DNS has support of ALIAS in preview.

Although I'm not really comfortable with coding and adding a PR, I am completely  volonteer to test it if needed.

Best regards, 
Marc

**Comment by ross** [comment]
Will throw this into the hopper, but tbh I'm building up quite a list at this point and not getting to spend a lot of time working through it. Others may get to it before I do.

**Comment by npaufler** [comment]
https://github.com/octodns/octodns-googlecloud/pull/25

This looks to work for me when testing locally. I'm not super familiar with the python testing framework so I think I've got everything in there with tests passing now, but let me know if this is all we need.

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns-googlecloud/pull/25

**Comment by npaufler** [comment]
@ross On what cadence do you usually generate new releases? I'd like to test this against our staging environment now that it's merged.

Cheers and thanks!

**Comment by ross** [comment]
Ad-hoc. Figured I'd give @WhatshallIbreaktoday a chance to say whether it worked for them or not and then cut one here.

**Comment by WhatshallIbreaktoday** [comment]
Works like a charm !

Warning regarding ALIAS is no more shown, and the change is nooped and applied on my test zone.

Thanks you both !
