### ISSUE TITLE
Feature Request: handle public / private zones

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [octodns/octodns-googlecloud#23]
Cloud DNS apis  identifies public from private zones by using a "visibility" field:

[https://cloud.google.com/dns/docs/reference/v1/managedZones](https://cloud.google.com/dns/docs/reference/v1/managedZones):

visibility | string | The zone's visibility: public zones are exposed to the  Internet, while private zones are visible only to Virtual Private Cloud  resources.           Acceptable values are:                        "private"             "public"

Today the default behaviour is to create the zone (on public side) if it does not exist.

If the zone exists internally, octodns will use the internal zone.

In case of split Horizon use case (same zone with different data ), It could be interresting to specify which zone we target.

Again, can help on testing.

Best regards, 
Marc

**Comment by ross** [comment]
Will throw this into the hopper, but tbh I'm building up quite a list at this point and not getting to spend a lot of time working through it. Others may get to it before I do.
