### ISSUE TITLE
Feature Request: support routing policies

### ISSUE THREAD

**Issue by alvarogonzalez-packlink** [octodns/octodns-googlecloud#35]
When I try to dump a record that has routing policies ( i.e. weighted round robin ), it throws an error. Also, there's still no way of describing that on the YAML config files (AFAIK).

In this case I have the record `api.mydomain.com` that has a weighted round robin policy between 2 IPs:

```console
% octodns-dump --config-file=config/gcp.yaml --output-dir=tmp/ mydomain.com. googlecloud
2023-09-01T11:31:46  [8541478400] INFO  Manager __init__: config_file=config/gcp.yaml, (octoDNS 1.0.0rc0)
2023-09-01T11:31:46  [8541478400] INFO  Manager _config_executor: max_workers=4
2023-09-01T11:31:46  [8541478400] INFO  Manager _config_include_meta: include_meta=False
2023-09-01T11:31:46  [8541478400] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-09-01T11:31:46  [8541478400] INFO  Manager __init__: global_processors=[]
2023-09-01T11:31:46  [8541478400] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.0.0rc0)
/Users/alvaro/Documents/repos/octodns/venv/lib/python3.10/site-packages/google/auth/_default.py:78: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
2023-09-01T11:31:47  [8541478400] INFO  Manager __init__: provider=googlecloud (octodns_googlecloud 0.0.3)
2023-09-01T11:31:47  [8541478400] INFO  Manager __init__: processor=not-dev-envs (octodns.processor.filter 1.0.0rc0)
2023-09-01T11:31:47  [8541478400] INFO  Manager __init__: plan_output=markdown (octodns.provider.plan 1.0.0rc0)
2023-09-01T11:31:47  [8541478400] INFO  Manager dump: zone=mydomain.com., output_dir=tmp/, output_provider=None, lenient=False, split=False, sources=['googlecloud']
2023-09-01T11:31:47  [8541478400] INFO  Manager dump: using custom YamlProvider
Traceback (most recent call last):
  File "/Users/alvaro/Documents/repos/octodns/venv/bin/octodns-dump", line 8, in <module>
    sys.exit(main())
  File "/Users/alvaro/Documents/repos/octodns/venv/lib/python3.10/site-packages/octodns/cmds/dump.py", line 48, in main
    manager.dump(
  File "/Users/alvaro/Documents/repos/octodns/venv/lib/python3.10/site-packages/octodns/manager.py", line 805, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/alvaro/Documents/repos/octodns/venv/lib/python3.10/site-packages/octodns_googlecloud/__init__.py", line 256, in populate
    record = Record.new(zone, record_name, data, source=self)
  File "/Users/alvaro/Documents/repos/octodns/venv/lib/python3.10/site-packages/octodns/record/base.py", line 62, in new
    raise ValidationError(fqdn, reasons)
octodns.record.exception.ValidationError: Invalid record api.mydomain.com.
  - missing value(s)
```

**Comment by alvarogonzalez-packlink** [comment]
If I have the time, I'll try to add it, although I'm kinda busy right now.

**Comment by ross** [comment]
There's two levels to this. The first one is the `--lenient` flag to octoDNS dump which is intended for situations like this where an existing record doesn't meet octoDNS's expectations/requirements. You should (hopefully) be able to get a successful dump if you include that flag in the `octodns-dump` call. The record(s) using unsupported features will be ~placeholders without valid/working data, but that's as designed/intended.

The second level is that `GoogleCloudProvider` doesn't support `dynamic` records which would include weighted and/or geo targeting. 

https://github.com/octodns/octodns-googlecloud/blob/06968e4944bb32f368876e7f2aca79f69208c7ac/octodns_googlecloud/__init__.py#L43

That's why an invalid record is being created. The provider doesn't look at the dynamic bits and since there's nothing in in the basic form the result is invalid.

It looks like Google Cloud DNS does support some geo targeting, https://cloud.google.com/blog/products/networking/dns-routing-policies-for-geo-location--weighted-round-robin, no clue if it's full featured and enough of a match for octoDNS's `dynamic` concept.  There are currently no plans to add `dynamic` support. It's generally a fairly involved process and can take a week or more of solid full-time work depending on how well things line up.

**Comment by alvarogonzalez-packlink** [comment]
Thanks for the `--lenient` flag, I didn't notice it. I'll try that meanwhile, as this is just one individual case among a thousand or two records. I'll be fine :)

Regarding the other stuff, I haven't check dynamic records until now, as I though it referred to the classic `dyndns` case, so I've done a quick review now, and this are my comments:

Google's round robin and geo location records to me look more like the current octoDNS geo records (or even simpler), as you can't subordinate rules and create a graph.

- It's only "weight" or "geo", not both at the same time
- The structure is, ahem, flatter, as you only define pairs of "weight" or "geo" and "rrdata"
- Health checks, geofencing and failover/fallback options don't apply to _us_, as those only work when you're using Google Cloud Load Balancer references as targets, and not IP addresses.
- No subnet addressing
- No rule ordering
- No catch-all (When there are no records defined for your geo area, Google Cloud DNS just answers with the nearest region with records)

A weighted round robin API call goes like this:

```json
{
  "name": "weighted.testdomain.com.",
  "routingPolicy": {
    "wrr": {
      "item": [
        {
          "weight": 10.0,
          "rrdata": [
            "1.1.1.1",
            "1.1.1.2",
            "1.1.1.3"
          ]
        },
        {
          "weight": 20.0,
          "rrdata": [
            "2.2.2.1",
            "2.2.2.2",
            "2.2.2.3"
          ]
        }
      ]
    }
  },
  "ttl": 300,
  "type": "A"
}
```

Geo routing call:
```json
{
  "name": "routed.testdomain.com.",
  "routingPolicy": {
    "geo": {
      "item": [
        {
          "location": "europe-central2",
          "rrdata": [
            "1.1.1.1",
            "1.1.1.2",
            "1.1.1.3"
          ]
        },
        {
          "location": "us-west4",
          "rrdata": [
            "2.2.2.1",
            "2.2.2.2",
            "2.2.2.3"
          ]
        }
      ],
      "enableFencing": false
    }
  },
  "ttl": 300,
  "type": "A"
}
```

Do you feel like this could be added somewhere else than `dynamic` ?

**Comment by ross** [comment]
> Regarding the other stuff, I haven't check dynamic records until now, as I though it referred to the classic `dyndns` case, so I've done a quick review now, and this are my comments:

Yeah. Naming stuff is hard :grin:
 
> Google's round robin and geo location records to me look more like the current octoDNS geo records (or even simpler), as you can't subordinate rules and create a graph.

Thanks. Definitely appreciate the 👀 on it.

> * It's only "weight" or "geo", not both at the same time
> * ...

TBH I can't remember if I did a (brief) survey of Google's stuff and came to the same conclusion, that it wasn't flexible enough to support octoDNS's concept. 

That said octoDNS has expanded functionality over the intervening years and could now export doing partial `dynamic` support. It's not really something any other providers have done, but `GoogleCloudProvider` could in theory take a look at the configured `dynamic` record and decide whether or not it can support it and either error out if not or modify the record in some sensible way.

That's likely not going to allow it support any geo targeting or health checking. It could at least let people to do weighted round robin and "simple" things like that.

**Comment by alvarogonzalez-packlink** [comment]
Nice. I have a bit of work around here to do, so maybe I can't do much python this days, but as I think I read that you aren't usually touching Google Cloud stuff, let me know :

- if you have any doubts about Google Cloud DNS products ( I'm not affiliated with Google at all, but I use GCP daily)
- if you need access to a GCP account to test DNS API calls

👌

**Comment by ross** [comment]
Heh. I think the google cloud setup I the last time I worked on anything was part of a setup for some testing/eval I did at GitHub so I probably don't have access ATM.  Doesn't look like there's a free tier either so I may hit you up if/when I get a chance to look at it.

**Comment by alvarogonzalez-packlink** [comment]
There's no free tier for DNS, so let me know if you need it :)
